import { escapeHTML as h } from "./io.js";

const style = `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#182b3c;background:#f3f6f8}*{box-sizing:border-box}body{margin:0}header{background:#142c3d;color:white;padding:22px max(24px,calc((100vw - 1040px)/2))}header small{color:#a5c0ce;display:block;margin-top:5px}main{max-width:1088px;margin:36px auto;padding:0 24px}h1{font-size:32px;letter-spacing:-1px;margin:0 0 10px}h2{font-size:19px;margin:0 0 16px}p{line-height:1.6;color:#4b6170}.grid{display:grid;grid-template-columns:1.2fr 1fr;gap:22px}.card{background:white;border:1px solid #dce5ea;border-radius:16px;padding:26px;margin-bottom:22px;box-shadow:0 4px 14px #19354805}.badge{font-size:12px;background:#d6ebe2;color:#205846;border-radius:20px;padding:5px 10px;display:inline-block;margin-bottom:20px}.muted{color:#637a88;font-size:14px}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}label{display:block;margin:15px 0 8px;font-size:14px}input,select{padding:11px;border:1px solid #b7c9d4;border-radius:8px;font:inherit;max-width:100%;background:white}button{border:0;border-radius:8px;padding:12px 17px;background:#235e72;color:white;cursor:pointer;font:inherit}button:hover{background:#17485b}button:focus-visible,a:focus-visible{outline:3px solid #efb84a;outline-offset:3px}button.secondary{background:#e5eef3;color:#224657}.traffic{font-size:34px;letter-spacing:5px;margin:12px 0}.state{font-size:21px;font-weight:650}ul{padding-left:20px;line-height:1.9}code{background:#edf3f6;border-radius:4px;padding:3px 6px}#result{min-height:24px;font-size:14px;color:#235e72}a{color:#235e72}.narrow{max-width:620px}.note{border-left:3px solid #dda341;padding-left:14px}pre{white-space:pre-wrap;font-size:12px;max-height:200px;overflow:auto;color:#486070}@media(max-width:740px){.grid{grid-template-columns:1fr}main{margin-top:24px}h1{font-size:27px}}`;
function page(title, body, script = "", nonce = "") {
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)} · Company OpenCode</title><style>${style}</style></head><body><header><strong>Company / Developer Platform</strong><small>Корпоративный OpenCode · локальный прототип</small></header>${body}${script ? `<script nonce="${nonce}">${script}</script>` : ""}</body></html>`;
}
export function loginPage(request, users, nonce) {
  const script = `document.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{accept:'application/json'},body:new URLSearchParams(new FormData(form))});if(!response.ok)throw Error();const result=await response.json();window.location.assign(result.redirect)}catch{document.querySelector('#login-error').textContent='Вход не завершён. Повторите /login в OpenCode.';button.disabled=false}}`;
  return page("Вход", `<main class="narrow"><span class="badge">Демонстрационный SSO</span><h1>Войти в рабочее пространство</h1><p>OpenCode запрашивает корпоративный конфиг и доступ к каталогу skills.</p><div class="card"><form method="post" action="/oauth/approve"><input type="hidden" name="requestID" value="${h(request.id)}"><input type="hidden" name="csrf" value="${h(request.csrf)}"><label for="account">Тестовая учётная запись</label><select id="account" name="account">${users.map(u => `<option value="${u.id}">${h(u.name)} — ${h(u.role)}</option>`).join("")}</select><p class="note">Это эмулятор. Здесь не нужно вводить корпоративный пароль.</p><button type="submit">Войти и вернуться в OpenCode</button><p id="login-error" role="alert"></p></form></div><p class="muted">Ссылка действует 5 минут. Токен будет передан плагину через одноразовый код; в адресной строке токена не будет.</p></main>`, script, nonce);
}
export function adminPage(token, nonce) {
  const body = `<main><span class="badge">Server emulator</span><h1>Корпоративный контур</h1><p>Управляйте ответами сервера и наблюдайте, как плагин реагирует на изменения.</p><div class="grid"><section><div class="card"><h2>Нагрузка на инференс</h2><div class="traffic" id="light" aria-live="polite">⚪</div><div class="state" id="load">Загрузка…</div><p id="loadMessage"></p><div class="row"><button data-level="green">🟢 Норма</button><button data-level="yellow">🟡 Высокая</button><button data-level="red">🔴 Перегрузка</button></div><p class="muted">Плагин проверяет нагрузку каждые 30 секунд и уведомляет при смене цвета.</p></div><div class="card"><h2>Версия конфига <span id="revision">—</span></h2><form id="config"><label for="modelName">Название корпоративной модели</label><input id="modelName" value="Company Code Demo" required maxlength="100"><label for="context">Контекст модели</label><input id="context" type="number" min="8192" max="2000000" value="128000" required><p><button>Опубликовать новую версию</button></p></form><p class="muted">После публикации выполните <code>/refresh_config</code> или дождитесь автоматической проверки.</p></div></section><section><div class="card"><h2>Проверка сбоев</h2><p>Временно отключите API или завершите все тестовые сессии.</p><div class="row"><button class="secondary" id="offline">Включить сбой API</button><button class="secondary" id="expire">Завершить сессии</button></div><p id="result" role="status"></p></div><div class="card"><h2>Команды OpenCode</h2><ul><li><code>/login</code> — вход в браузере</li><li><code>/refresh_config</code> — обновить конфиг</li><li><code>/skills_load</code> — выбрать skills</li><li><code>/inference_status</code> — светофор</li><li><code>/corp_status</code> — диагностика</li><li><code>/logout</code> — выход</li></ul></div><div class="card"><h2>События сервера</h2><p class="muted">Журнал содержит действия и версии. Токены и содержимое запросов к модели не записываются.</p><pre id="audit"></pre></div></section></div></main>`;
  const script = `const token=${JSON.stringify(token)};let offline=false;const labels={green:'Доступен',yellow:'Повышенная нагрузка',red:'Перегрузка'},lights={green:'🟢',yellow:'🟡',red:'🔴'};async function state(){try{const r=await fetch('/admin/state',{headers:{'x-demo-admin':token}});if(!r.ok)throw Error(r.status);const s=await r.json();offline=s.offline;document.querySelector('#light').textContent=offline?'⚪':lights[s.level];document.querySelector('#load').textContent=offline?'API недоступен':labels[s.level];document.querySelector('#loadMessage').textContent='Очередь: '+s.queue+' · активных токенов: '+s.activeTokens;document.querySelector('#revision').textContent=s.revision;document.querySelector('#offline').textContent=offline?'Восстановить API':'Включить сбой API';document.querySelector('#audit').textContent=s.audit.slice(-12).reverse().map(e=>e.at+'  '+e.action+(e.detail?' · '+e.detail:'')).join('\\n')}catch{document.querySelector('#result').textContent='Сервер недоступен'}}async function change(body){try{const r=await fetch('/admin/state',{method:'POST',headers:{'content-type':'application/json','x-demo-admin':token},body:JSON.stringify(body)});if(!r.ok)throw Error();document.querySelector('#result').textContent='Изменение применено';await state()}catch{document.querySelector('#result').textContent='Не удалось применить изменение'}}document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>change({level:b.dataset.level}));document.querySelector('#offline').onclick=()=>change({offline:!offline});document.querySelector('#expire').onclick=()=>change({expire:true});document.querySelector('#config').onsubmit=e=>{e.preventDefault();change({publish:true,modelName:document.querySelector('#modelName').value,context:Number(document.querySelector('#context').value)})};state();setInterval(state,2000);`;
  return page("Панель эмулятора", body, script, nonce);
}
