// YADRO-inspired palette and typography. Proxima Nova is used if it is installed;
// system fallbacks keep the local emulator self-contained and offline.
export const style = `
:root{font-family:"Proxima Nova","Helvetica Neue",Arial,sans-serif;color:#202329;background:#f5f6f8;font-size:16px;font-synthesis:none}
*{box-sizing:border-box}body{margin:0;min-width:320px}button,input,select{font:inherit}button{cursor:pointer}button:disabled{cursor:wait;opacity:.65}
button:focus-visible,input:focus-visible,select:focus-visible,a:focus-visible{outline:3px solid #6865e6;outline-offset:3px}
.site-header{background:#17191f;color:#fff}.header-inner{max-width:1320px;margin:auto;min-height:82px;padding:0 40px;display:flex;align-items:center;justify-content:space-between;gap:24px}
.brand{display:flex;align-items:center;gap:14px;color:inherit}.brand-mark{width:38px;height:38px;display:grid;place-items:center;background:#3029a9;color:#fff;font-size:23px;font-weight:700;line-height:1;letter-spacing:-.08em}
.brand-name{font-size:17px;font-weight:700;letter-spacing:.01em}.brand-subtitle{display:block;color:#a8abb5;font-size:12px;font-weight:400;letter-spacing:.02em;margin-top:2px}
.header-meta{display:flex;align-items:center;gap:10px;color:#c5c6cf;font-size:13px;white-space:nowrap}.header-meta::before{content:"";width:7px;height:7px;border-radius:50%;background:#8ed9ad;box-shadow:0 0 0 4px #8ed9ad1e}
main{max-width:1320px;margin:0 auto;padding:44px 40px 72px}.eyebrow{color:#3029a9;text-transform:uppercase;letter-spacing:.15em;font-size:12px;font-weight:700}
.page-heading{display:flex;align-items:end;justify-content:space-between;gap:24px;margin:13px 0 34px}h1{font-size:clamp(38px,4vw,56px);font-weight:500;letter-spacing:-.04em;line-height:1.03;margin:0}
.lead{margin:13px 0 0;color:#616775;font-size:17px;line-height:1.5;max-width:690px}.page-index{font-size:12px;color:#8d919c;letter-spacing:.1em;white-space:nowrap;padding-bottom:5px}
.dashboard{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(340px,1fr);gap:18px;align-items:start}.stack{display:grid;gap:18px;min-width:0}
.card{background:#fff;border:1px solid #e2e4ea;border-radius:12px;padding:28px;min-width:0}.card-head{display:flex;align-items:start;justify-content:space-between;gap:18px;margin-bottom:24px}
.section-number{color:#a2a6b0;font-size:11px;font-weight:700;letter-spacing:.13em}h2{font-size:23px;font-weight:600;line-height:1.15;letter-spacing:-.02em;margin:8px 0 0}.section-copy{font-size:14px;color:#737987;line-height:1.5;margin:8px 0 0}
.status-display{display:flex;align-items:center;gap:18px;padding:24px 0;border-top:1px solid #eceef2;border-bottom:1px solid #eceef2}.status-symbol{width:66px;height:66px;border-radius:50%;display:grid;place-items:center;flex:none;background:#e7f5eb}
.status-symbol::after{content:"";width:25px;height:25px;border-radius:50%;background:#21a656;box-shadow:0 0 0 8px #21a65620}.status-symbol[data-state="yellow"]{background:#fff4d8}.status-symbol[data-state="yellow"]::after{background:#dfad2c;box-shadow:0 0 0 8px #dfad2c24}
.status-symbol[data-state="red"]{background:#fbe5e5}.status-symbol[data-state="red"]::after{background:#d85353;box-shadow:0 0 0 8px #d8535324}.status-symbol[data-state="offline"]{background:#eceef1}.status-symbol[data-state="offline"]::after{background:#9298a4;box-shadow:0 0 0 8px #9298a424}
.status-kicker{color:#858a96;text-transform:uppercase;letter-spacing:.12em;font-size:11px;font-weight:700}.status-title{font-size:30px;line-height:1.1;letter-spacing:-.03em;font-weight:600;margin:5px 0 4px}.status-detail{color:#6e7480;font-size:14px;line-height:1.4;margin:0}
.metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:22px 0 26px}.metric{border-left:2px solid #3029a9;padding-left:14px}.metric-value{font-size:28px;line-height:1;font-weight:600;letter-spacing:-.03em;display:block}.metric-label{color:#7a808d;font-size:13px;display:block;margin-top:7px}
.control-label{display:block;font-size:12px;font-weight:700;letter-spacing:.11em;text-transform:uppercase;color:#858a96;margin-bottom:11px}.level-controls{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}
.level-button{border:1px solid #dde0e7;background:#f8f9fb;color:#373d49;border-radius:7px;padding:12px 10px;font-size:14px;font-weight:600;white-space:nowrap;transition:background .15s,border-color .15s,box-shadow .15s}.level-button:hover{border-color:#aaa7df;background:#f3f2ff}.level-button[aria-pressed="true"]{background:#efeeff;border-color:#3029a9;color:#29249a;box-shadow:inset 0 0 0 1px #3029a9}
.level-button::before{content:"";display:inline-block;width:7px;height:7px;margin-right:8px;border-radius:50%;background:#25a95a;vertical-align:1px}.level-button[data-level="yellow"]::before{background:#e1ad2e}.level-button[data-level="red"]::before{background:#d95252}
.helper{color:#868b96;font-size:13px;line-height:1.45;margin:15px 0 0}.revision{display:inline-flex;align-items:center;background:#efeeff;color:#3029a9;border-radius:5px;padding:5px 9px;font-size:12px;font-weight:700;white-space:nowrap}
.field-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,.5fr);gap:14px}label{display:block;margin:0 0 8px;color:#4b5260;font-size:13px;font-weight:600}input,select{width:100%;min-height:46px;padding:10px 13px;border:1px solid #ced2db;border-radius:7px;background:#fff;color:#202329;font-size:15px}input:hover,select:hover{border-color:#979eac}
.form-footer{border-top:1px solid #eceef2;margin-top:24px;padding-top:21px;display:flex;align-items:center;justify-content:space-between;gap:18px}.form-footer .helper{margin:0;max-width:380px}
.primary{border:1px solid #3029a9;border-radius:7px;background:#3029a9;color:#fff;padding:12px 18px;font-size:14px;font-weight:600;white-space:nowrap;transition:background .15s,transform .15s}.primary:hover{background:#211c88;transform:translateY(-1px)}
.secondary{border:1px solid #d7dae2;border-radius:7px;background:#fff;color:#333a48;padding:11px 15px;font-size:14px;font-weight:600;transition:border-color .15s,background .15s}.secondary:hover{border-color:#9e9bcf;background:#f7f6ff}.secondary[aria-pressed="true"]{color:#b43c43;border-color:#e3b7bb;background:#fff5f5}
.action-list{display:grid;gap:10px}.action-item{border:1px solid #e6e8ed;border-radius:8px;padding:15px 16px;display:flex;align-items:center;justify-content:space-between;gap:16px}.action-item strong{display:block;font-size:15px;font-weight:600}.action-item small{display:block;color:#858a96;font-size:12px;line-height:1.4;margin-top:4px}
.feedback{min-height:20px;margin:15px 0 0;color:#3029a9;font-size:13px;font-weight:600}.feedback[data-kind="error"]{color:#b43c43}.commands{list-style:none;margin:0;padding:0;border-top:1px solid #eceef2}.commands li{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-bottom:1px solid #eceef2;font-size:13px;color:#777e8b}
code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:#3029a9;background:#f1f0fc;border-radius:4px;padding:3px 5px;white-space:nowrap}.audit-card{grid-column:1/-1}.audit-header{margin-bottom:18px}.audit{margin:0;padding:18px 20px;background:#191c25;color:#d5d9e5;border-radius:7px;font:12px/1.8 ui-monospace,SFMono-Regular,Menlo,monospace;min-height:96px;max-height:230px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}.audit:empty::before{content:"Событий пока нет";color:#9299aa}
.login-shell{max-width:760px;margin:0 auto;padding-top:72px}.login-shell .page-heading{margin-bottom:28px}.login-card{padding:36px}.login-card label{margin-top:22px}.login-card .primary{margin-top:24px}.notice{margin-top:22px;padding:15px 17px;border-left:3px solid #3029a9;background:#f6f6fc;color:#505769;font-size:14px;line-height:1.5}.login-footnote{font-size:13px;color:#838895;line-height:1.5;margin:22px 0 0}
@media(max-width:980px){.dashboard{grid-template-columns:1fr}.audit-card{grid-column:auto}.page-index{display:none}}
@media(max-width:640px){.header-inner{padding:0 20px;min-height:70px}.header-meta{font-size:0;gap:0}.header-meta::before{width:9px;height:9px}main{padding:32px 18px 48px}.page-heading{margin-bottom:25px}.card{padding:21px}.status-display{gap:14px}.status-symbol{width:56px;height:56px}.status-title{font-size:25px}.field-grid{grid-template-columns:1fr}.form-footer{align-items:stretch;flex-direction:column}.form-footer .primary{width:100%}.action-item{align-items:stretch;flex-direction:column}.action-item button{width:100%}.level-button{font-size:12px;padding:12px 5px}.level-button::before{margin-right:5px}.commands li{flex-direction:column;gap:3px}.login-shell{padding-top:38px}.login-card{padding:24px}}
`;
